title: "Naqvi Industrial"
author: "Sameer Abbas"
description: "Powered by Naqvi Industrial ©        --Innovation In Your Hands--"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the us, title: "Our CEO", icon, user-tie-hairual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Our CEO", icon, user-tie}
  - {file: "README.md", title: "Services", icon, brief}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "s.abbas5@hotmail.com"}
  - {title: Github, icon: github, url: "https://github.com/sabbas55"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
